version: "3"
services:
  sgr-frontend:
    build:
      context: .
      dockerfile: ./front/dev.Dockerfile
    container_name: sgr-frontend
    image: sgr-frontend
    restart: always
    volumes:
      - /usr/app/service
      - ./front/src:/usr/frontend/src
      - ./front/dist:/usr/frontend/dist
    networks:
      - "sgr-network"
    ports:
      - "4000:4000"
  sgr-backend:
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    container_name: sgr-backend
    image: sgr-backend
    restart: always
    volumes:
      - /usr/app/service
      - ./backend:/usr/backend/app
      - ./backend/dist:/usr/backend/dist
    networks:
      - "sgr-network"
    ports:
      - "13331:13331"
networks:
  sgr-network:
    driver: bridge