version: "3"
services:
  sgr-frontend:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    container_name: sgr-frontend
    image: sgr-frontend
    depends_on:
      - sgr-backend
    restart: always
    volumes:
      - ./front:/usr/src/app
      - ./front/src:/usr/src/app/src
      - ./front/dist:/usr/src/app/dist
    networks:
      - sgr-network
    ports:
      - "9000:9000"
  sgr-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: sgr-backend
    image: sgr-backend
    restart: always
    depends_on:
      - sgr-database
    volumes:
      - ./backend:/usr/src/app
      - ./backend/dist:/usr/src/app/dist
    networks:
      - sgr-network
    ports:
      - "9001:9001"
  sgr-database:
    container_name: sgr-database
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./database/my.cnf:/etc/mysql/my.cnf
    networks:
      - sgr-network
    ports:
      - "9002:9002"

networks:
  sgr-network:
    name: sgr-network
    driver: bridge