version: "3"
services:
  sgr-frontend:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    container_name: sgr-frontend
    image: sgr-frontend
    depends_on:
      - sgr-backend
    restart: always
    networks:
      - sgr-network
    ports:
      - "9000:9000"
  sgr-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: sgr-backend
    image: sgr-backend
    restart: always
    env_file:
      - .env
    environment:
      - FRONTEND_URI=${FRONTEND_URI}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - EXPRESS_HOST=${EXPRESS_HOST}
      - EXPRESS_PORT=${EXPRESS_PORT}
    depends_on:
      - sgr-database
    networks:
      - sgr-network
    ports:
      - "9001:9001"
  sgr-database:
    container_name: sgr-database
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ./database/my.cnf:/etc/mysql/my.cnf
    networks:
      - sgr-network
    ports:
      - "9002:9002"

networks:
  sgr-network:
    name: sgr-network
    driver: bridge