version: "3"
services:
  sgr-frontend:
    build:
      context: ./front
      dockerfile: ./dev.Dockerfile
    container_name: sgr-frontend
    image: sgr-frontend
    restart: always
    volumes:
      - ./front:/usr/src/app
      - ./front/src:/usr/src/app/src
      - ./front/dist:/usr/src/app/dist
    networks:
      - "sgr-network"
    ports:
      - "4000:4000"
  sgr-backend:
    build:
      context: ./backend
      dockerfile: ./dev.Dockerfile
    container_name: sgr-backend
    image: sgr-backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - ./backend/dist:/usr/src/app/dist
    networks:
      - "sgr-network"
    ports:
      - "13331:13331"
networks:
  sgr-network:
    driver: bridge